name: Snyk Infrastructure
on: push

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Run Snyk Scanning
        uses: eeveebank/github-actions-snyk@v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.PLATFORM_SNYK_TOKEN }}
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
